version: 2.1
jobs:
  build:
    adhoc:
      macos:
        xcode: 14.2.0
      environment:
        FL_OUTPUT_DIR: output
        FASTLANE_LANE: adhoc
      steps:
        - checkout
        - run: bundle install
        - run:
            name: Fastlane
            command: bundle exec fastlane $FASTLANE_LANE
        - store_artifacts:
            path: output