version: 2.1
jobs:
  build:
    macos:
      xcode: 14.2.0
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
     # - run: flutter build apk --release
     # - store_artifacts:
     #     path: build/app/outputs/flutter-apk/app-release.apk
      - run:
          name: Install CocoaPods
          command: pod install --verbose