version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/flutter:2.0.0
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: flutter pub get
      - run:
          name: Build Android APK
          command: flutter build apk --release
          when:
            branch: [main, develop]