version: '2.1'
orbs:
  android: circleci/android@1.0.3
  flutter: circleci/flutter@2.0.0
jobs:
  distribute:
    executor:
      name: android/android-machine
    steps:
      - flutter/install_sdk_and_pub:
          version: 3.0.3
      - flutter/install_android_gradle_dependencies
      - flutter/install_android_gem
      - run:
          command: bundle exec fastlane distribute
          working_directory: ios
      - run:
          name: Install Dependencies
          command: flutter pub get
      - run:
          name: Build Android APK
          command: flutter build apk --release
workflows:
  distribute:
    jobs:
      - distribute